### ISSUE TITLE
Change development to master

### ISSUE THREAD

**Issue by tayler6000** [tayler6000/pyVoIP#31]
Currently development of v1.6.0 is on its own branch.  In comparable projects, like CPython, master is usually where the latest development build resides and a branch will be made for a stable build that is still being maintained.

I propose we create the branch v1.5, and push all patches to 1.5 to that branch going forward; then merge v1.6.0-dev to master.

@Input-BDF As the only other official contributor to this project, I want your opinion specifically.  Please let me know your opinions in the comments.

**Comment by Input-BDF** [comment]
In my opinion this depends on your philosophy and if you want to support multiple versions parallel like [Grafana branch structure](https://github.com/grafana/grafana) where you have multiple major and minor version branches.

I favor having master as last stable release, develop as development branch (without any version numbers in the name). For fixes and new features again seperate branches created from develop, which are only merged into develop and deleted afterwards.
If develop gets into a milestone or an for the project stable release, develop is merged into master, but stays active. Master gets tagged with version number. Important hotfixes can be branched from master and merged back into, but this should be avoided if possible, cause then you also have to keept track of on dev.
More or the less the git-flow way from Driessen (cf.:  [here](https://nvie.com/posts/a-successful-git-branching-model/) or [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)). Even if it's quite old today, in my eyes it's relativly stable concept. Maybe a little bit heavy, but stable^^. The big decissions to make there is when to merge from develop into master and when to raise which version number part.

What you propose seems like [One-Flow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow) with additional version release branches (which are not neccessary, cause of tags). One-Flow has lesser overhead and you are more continiuosly in master but I think this can get hairy on bigger changes which are not really done with one feature.

Mainly I'm open to new ways and concepts ;)

**Comment by tayler6000** [comment]
Well another reason I would like to have develop as master is because the way GitHub works, an issue is only closed when a linked PR is merged with master.  And the thing you mentioned about hot fixes is why I don't necessarily like having developments not on master.  For example due to the release of 1.5.4 I have to pull those changes to 1.6.0 and since 1.5 and 1.6 are so different there are conflicts that are annoying and confusing to merge.

I agree the approach I'm proposing only makes sense if you're supporting more than one version (like the Long Term Stable concept Ubuntu has) but that's kind of what I intend with pyVoIP, at least for now.  We have been supporting 1.5 while developing 1.6 for example.  I also intend to support 1.6 for a while since we will be refactoring so many functions in 2.0.

I personally find having to merge an update for 1.5 to 1.6 really annoying as it's often either already patched in 1.6 or needs to be implemented in a different way or what have you.

Thoughts?

**Comment by Input-BDF** [comment]
Iirc GitHub closes issues on pullrequest made to the default branch (which could be set to develop) when using `closes #xyz` and it marks issues merged to nondefault branches with something like `will be closed when branch xyz will be merged to abc`. Little drawback of first approach: develop would be the first branch you see when visiting the project page (no yawbreaker for me)

Supporting two versions makes sence. Especially on large changes like you said huge refactoring plans, major changes on core functionality or switching to another 3rdparty module with bigger effects. Question here is how often the "large" part will happen.

Regarding the annoying part I'm missing some experience on working with multiple separate branches for versions. But in the end having master on last stable and develop it's more or the less the way to have two coexisting versions. The anoying part here starts as you said on fixing an issue on 1.5.x, raising to 1.5.x+1 and also keep track of these changes in 1.6.x. As hotfixes should be merged to both master and develop you still know what happend. I personally would only do this if the whole functionality is in danger by the issue. If not it's something for the develop branch and will be fixed in future releases (marked as stated in the beginning). Maybe also by documenting how the issue can be fixed in stable branch (e.g. with a patch file). The merge is as the name states a hotfix. But this "problem" exists independently of having master(stable), development(current) or version1.5(stable), master(current). Here just the naming is the different.

In the end which way ever you handle the branches one thing should be secured: Keeping at least two branches in an "productive" condition and keeping feature branches open and unmerged until the whole task is done. This can stop working on other branches on things like "let's refactor everything" but this also shouldn't happen so often.

But maybe I'm just thinking a bit to complicated cause I'm used to some workflow^^

**Comment by xyc0815** [comment]
I think first there should be a product roadmap. Will you have multiple versions like 1.5 for PBX only and a 1.6 for SIP server connection as example or do you want a slow moving LTS version and a fast moving feature drop version or something else. For each type you have different strategies for organizing your GIT tree.
Also thing about the time you have for the project. Do you have time to develop an support multiple versions?
For now I would start with a stable master and a development branch. Merging the development branch into master and tagging the versions in master. This is my two cents.
